[phases.setup]
npmVersion = "10"
nodeVersion = "20"

[phases.install]
cmds = [
  "cd /app/backend && npm install",
  "cd /app/frontend && npm install"
]

[phases.build]
cmds = [
  "cd /app/frontend && npm run build"
]

[start]
cmd = "cd /app/backend && node server.js"
