[phases.setup]
npmVersion = "10"
nodeVersion = "20"

[phases.install]
cmds = [
  "cd /app/backend && npm install",
  "cd /app/frontend && npm install"
]

[phases.build]
cmds = [
  "cd /app/frontend && npm run build",
  "mkdir -p /app/frontend/out",
  "ls -la /app/frontend/.next || echo '.next directory not found'",
  "ls -la /app/frontend/out || echo 'out directory not found'"
]

[start]
cmd = "cd /app/backend && node server.js"
